services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: knotree_cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - knotree-postgres:/var/lib/postgresql/data

volumes:
  knotree-postgres:
