{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "knotree-api.fullname" . }}
  labels:
    {{- include "knotree-api.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ .Values.certManager.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host | quote }}
{{- if .Values.ingress.apiHost }}
    - {{ .Values.ingress.apiHost | quote }}
{{- end }}
{{- if .Values.web.enabled }}
    - {{ .Values.web.ingress.host | quote }}
{{- end }}
{{- if .Values.env.appServicePublicDomain }}
    - {{ printf "img.%s" .Values.env.appServicePublicDomain | quote }}
{{- end }}
{{- end }}
